### PR TITLE
[fix #100] quote actual face

### LINKED ISSUE #100: error during redisplay: void-variable mode-line
Recently, spaceline-all-the-icons cannot work for me. I have tried to track why it is, but failed. 

If I disable this package, my emacs can work correctly. I have tried to test only with spaceline and spaceline-all-the-icons by only loading the two packages with `emacs -q`, and the issue is same.

output by `spaceline-all-the-icons--debug-segments`
```
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable mode-line) [62 times]
spaceline-all-the-icons--debug-segments:  Errors found in Spaceline Segments: [battery-status, buffer-id, buffer-path, buffer-size, eyebrowse-workspace, flycheck-status-info, flycheck-status, git-status, hud, mode-icon, modified, multiple-cursors, narrowed, neotree-close-bracket, neotree-context, neotree-dirs, neotree-files, neotree-index, neotree-open-bracket, nyan-cat, org-clock-current-task, package-updates, paradox-filter, paradox-line-count, paradox-status-installed, paradox-status-new, paradox-status-upgrade, paradox-total, position, process, projectile, region-info, separator-left-active-1, separator-left-active-2, separator-left-active-3, separator-left-active-4, separator-left-extra-1, separator-left-extra-2, separator-left-inactive, separator-minor-mode-left, separator-minor-mode-right, separator-paradox-1, separator-paradox-2, separator-paradox-3, separator-paradox-4, separator-right-active-1, separator-right-active-2, separator-right-inactive, sunrise, sunset, temperature, time, vc-icon, vc-status, weather, which-function, window-number]
```

### PR DESCRIPTION
**Pull request by LiuPai**
https://github.com/TheBB/spaceline/commit/ddd4907e4775dd0aa242936f1c8bfbb6bd1afae4
after this commit actual face need quote

### CODE REVIEW

**Comment by anmoljagetia** [comment]
Looks exactly like what I had to do to get it to work! (Y)
I was going to open a PR, but I found this, so will just do a +1 here.

@domtronn Thank you for writing and maintaining spaceline-all-the-icons (Y)

**Comment by stackcats** [comment]
Thanks @LiuPai

**Comment by skgsergio** [comment]
Checked out this PR and is working with master spaceline without problems. Thanks @LiuPai.

**Comment by mjgiarlo** [comment]
@domtronn @LiuPai super cool! looking forward to seeing this in a 1.4.1 release. thanks, all.

**Comment by mjgiarlo** [comment]
@domtronn @LiuPai s Do y'all intend to cut a new release with this fix? Or do you not think that is needed?

**Pull request merged**
