### PR TITLE
Adding conda environment (anaconda.org) segment.

### PR DESCRIPTION
**Pull request by jwintz**
See https://github.com/necaris/conda.el.

### CODE REVIEW

**Comment by jwintz** [comment]
Would love to colour it though, but it is not as straight-forward as I wish ;-)

**Comment by jwintz** [comment]
Hummm, for some reason it breaks the `buffer-position` and the `hud` segments, whenever its condition is not `true` ...

**Comment by domtronn** [comment]
I'm not familiar with **Conda** or **Anaconda** 😅 

What does `conda-env-current-name` look like?
Also, in your predicate, won't `conda-env-current-name` be nil if there isn't one?

And how does it break the `buffer-position`/`hud` segments?

**Comment by jwintz** [comment]
> What does conda-env-current-name look like?

It is defined as such:

```
(defvar conda-env-current-name nil "Name of current conda env.")
```

> Also, in your predicate, won't conda-env-current-name be nil if there isn't one?

```
(length nil) ;; => 0
```

So I guess it is fine ?

As for the `buffer-position`/`hud` segments, they only both appear when the `:when` condition of this segment holds.

I have then tried to use the vanilla `spaceline-all-the-icons`, but I can't these two to work together.

**Pull request closed without merging**
