### PR TITLE
Add current org mode clock task segment

### PR DESCRIPTION
**Pull request by alexmurray**

### CODE REVIEW

**Comment by spraharsh** [comment]
I don't really have the time to make the changes myself for some time but I would really like to see [time-elapsed/effort-estimate] like in powerline.

**Comment by domtronn** [comment]
Sorry for the huge delay... I've had a lot less time recently with new job and moving cities etc... 

I'm going to look through this branch now and hopefully get it merged in today :) I don't know a lot about org mode clock task, so if you could provide screenshots of what it's supposed to look like or any other information to recreate the desired behaviour, that would be really useful.

---

@spraharsh I'll have a look through powerline's code and see if I can easily port that as well 👍

**Comment by domtronn** [comment]
@alexmurray Looks good 👍

**Comment by spraharsh** [comment]
The idea behind org clock is to clock the amount of time that is spent on a task. An estimate for the amount of time expected can be made and compared against (called an effort estimate). 

Powerline shows the [time spent/effort estimate] and If time exceeds the effort estimate highlights the timer in red
Here's how it looks currently
btsc

Here's how it looks in powerline when the task exceeds the time limit and otherwise
thing2

thingy3

**Comment by VonFry** [comment]
I think this pr has some error with old version orgmode or those who don't use org clock.
Before I set with org clock, it has an error  about this. 
```
Error during redisplay: (eval (spaceline-ml-all-the-icons)) signaled (void-variable org-clock-current-task) [68 times]
```

**Comment by domtronn** [comment]
Should be fixed by #60

**Pull request merged**
